language: crystal
crystal:
  - latest
  - nightly
script:
  - crystal spec
  - crystal tool format --check
matrix:
  allow_failures:
    - crystal: nightly
before_script:
  - mkdir -p ./spec/assets/sessions/
